### ISSUE TITLE
Connecting to datasource

### ISSUE THREAD

**Issue by planetcomcreative** [unfolding-io/Astrorante#3]
![Screenshot 2024-08-28 105542](https://github.com/user-attachments/assets/35afefb9-7f1e-4461-8336-64092096dd7c)
I just setup the project but I'm having issues connecting to the data source. 

here is what I'm getting in my terminal: 

10:29:06 [ERROR] [vite] Error: cannot print server URLs before server.listen is called.
10:29:06 [WARN] [vite] 
A PostCSS plugin did not pass the `from` option to `postcss.parse`. This may cause imported assets to be incorrectly transformed. If you've recently added a PostCSS plugin that raised this warning, please contact the package author to fix the issue.
10:29:07 [astro-icon] Loaded icons from src/icons
10:29:08 [200] /setup 84ms
Error in searchListings: {
  message: 'Not Found',
  status: 404,
  response: 'This record could not be found'
}
10:29:09 [200] /api/setup/datasources/pull 524ms

**Comment by preetamslot** [comment]
Hi,
I have to investigate. can you let me know your OS and node version?

**Comment by jeffrey-agyepong** [comment]
Hi,
Thank you. I'm on Windows 11 and node version is 20.16.0

**Comment by planetcomcreative** [comment]
Hi,
Thank you. I'm on Windows 11 and node version is 20.16.0

**Comment by alvinChristianto** [comment]
got same error. my windows is 11 and node version is v20.3.0. is there any solution for this. the template looks nice

**Comment by preetamslot** [comment]
I will create a new storyblok account to test this bug.

**Comment by preetamslot** [comment]
@alvinChristianto @planetcomcreative .
Think I found the issue, it could be that new accounts have a more strict rate limit on the SB API.
I have updated the code, can you check?
If you get an error, first try the refresh button, then retry the sync.

**Comment by planetcomcreative** [comment]
> @alvinChristianto @planetcomcreative . Think I found the issue, it could be that new accounts have a more strict rate limit on the SB API. I have updated the code, can you check? If you get an error, first try the refresh button, then retry the sync.


Unfortunately, I still get a similar error:
09:07:29 [200] POST /api/setup/datasources/push 201ms
Error in searchListings: { message: 'Unauthorized', status: 401, response: 'Unauthorized' }
09:07:30 [200] POST /api/setup/datasources/push 342ms
Error in searchListings: { message: 'Unauthorized', status: 401, response: 'Unauthorized' }
09:07:31 [200] POST /api/setup/datasources/push 195ms
Error in searchListings: { message: 'Unauthorized', status: 401, response: 'Unauthorized' }
09:07:32 [200] /api/setup/components/pull 344ms
Error in searchListings: { message: 'Unauthorized', status: 401, response: 'Unauthorized' }
09:07:33 [200] /api/setup/stories/pull 337ms

**Comment by preetamslot** [comment]
Even with a new SB account I never had the Unauthorized error form SB API :(
this looks more like a API issue, somehow your personal token has not enough rights to your space.
:(

I am closing this issue for now.
